name = "guardivex"
type = "javascript"
compatibility_date = "2026-05-21"

[env.production]
vars = { ENVIRONMENT = "production" }

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[[static_assets]]
binding = "ASSETS"
directory = "./dist"
include = ["**/*"]

[site]
bucket = "./dist"
include = ["**/*"]
